python process_raw_images.py data/street/real001.jpg /tmp/output/street_001_
python process_raw_images.py data/street/real002.jpg /tmp/output/street_002_
python process_raw_images.py data/street/real003.jpg /tmp/output/street_003_
python process_raw_images.py data/street/real004.jpg /tmp/output/street_004_
python process_raw_images.py data/street/real005.jpg /tmp/output/street_005_
python process_raw_images.py data/street/real006.jpg /tmp/output/street_006_
python process_raw_images.py data/street/real007.jpg /tmp/output/street_007_
python process_raw_images.py data/street/real008.jpg /tmp/output/street_008_
python process_raw_images.py data/street/real009.jpg /tmp/output/street_009_
python process_raw_images.py data/street/real010.jpg /tmp/output/street_010_
python process_raw_images.py data/street/real011.jpg /tmp/output/street_011_
python process_raw_images.py data/street/real012.jpg /tmp/output/street_012_
python process_raw_images.py data/street/real013.jpg /tmp/output/street_013_
python process_raw_images.py data/street/real014.jpg /tmp/output/street_014_
python process_raw_images.py data/street/real015.jpg /tmp/output/street_015_
python process_raw_images.py data/street/real016.jpg /tmp/output/street_016_
python process_raw_images.py data/street/real017.jpg /tmp/output/street_017_
python process_raw_images.py data/street/real018.jpg /tmp/output/street_018_
python process_raw_images.py data/street/real019.jpg /tmp/output/street_019_
python process_raw_images.py data/street/real020.jpg /tmp/output/street_020_
python process_raw_images.py data/street/real021.jpg /tmp/output/street_021_
python process_raw_images.py data/street/real022.jpg /tmp/output/street_022_
python process_raw_images.py data/street/real023.jpg /tmp/output/street_023_
python process_raw_images.py data/street/real024.jpg /tmp/output/street_024_
python process_raw_images.py data/street/real025.jpg /tmp/output/street_025_
python process_raw_images.py data/street/real026.jpg /tmp/output/street_026_
python process_raw_images.py data/street/real027.jpg /tmp/output/street_027_
python process_raw_images.py data/street/real028.jpg /tmp/output/street_028_
python process_raw_images.py data/street/real029.jpg /tmp/output/street_029_
python process_raw_images.py data/street/real030.jpg /tmp/output/street_030_
python process_raw_images.py data/street/real031.jpg /tmp/output/street_031_
python process_raw_images.py data/street/real032.jpg /tmp/output/street_032_
python process_raw_images.py data/street/real033.jpg /tmp/output/street_033_

python process_raw_images.py data/metalslug/metalslug001.jpg /tmp/output/metalslug_001_
python process_raw_images.py data/metalslug/metalslug003.gif /tmp/output/metalslug_003_
python process_raw_images.py data/metalslug/metalslug004.jpg /tmp/output/metalslug_004_
python process_raw_images.py data/metalslug/metalslug005.gif /tmp/output/metalslug_005_
python process_raw_images.py data/metalslug/metalslug006.gif /tmp/output/metalslug_006_
python process_raw_images.py data/metalslug/metalslug007.png /tmp/output/metalslug_007_
python process_raw_images.py data/metalslug/metalslug008.png /tmp/output/metalslug_008_
python process_raw_images.py data/metalslug/metalslug009.png /tmp/output/metalslug_009_
python process_raw_images.py data/metalslug/metalslug010.png /tmp/output/metalslug_010_
python process_raw_images.py data/metalslug/metalslug011.jpg /tmp/output/metalslug_011_
python process_raw_images.py data/metalslug/metalslug012.png /tmp/output/metalslug_012_
python process_raw_images.py data/metalslug/metalslug013.gif /tmp/output/metalslug_013_
python process_raw_images.py data/metalslug/metalslug013.jpg /tmp/output/metalslug_013_
python process_raw_images.py data/metalslug/metalslug014.jpg /tmp/output/metalslug_014_
python process_raw_images.py data/metalslug/metalslug016.png /tmp/output/metalslug_016_
python process_raw_images.py data/metalslug/metalslug017.png /tmp/output/metalslug_017_
