python process_raw_images.py data/real/real001.jpg /tmp/output/real_001_
python process_raw_images.py data/real/real002.jpg /tmp/output/real_002_
python process_raw_images.py data/real/real003.jpg /tmp/output/real_003_
python process_raw_images.py data/real/real004.jpg /tmp/output/real_004_
python process_raw_images.py data/real/real005.jpg /tmp/output/real_005_
python process_raw_images.py data/real/real006.jpg /tmp/output/real_006_
python process_raw_images.py data/real/real007.jpg /tmp/output/real_007_
python process_raw_images.py data/real/real008.jpg /tmp/output/real_008_
python process_raw_images.py data/real/real009.jpg /tmp/output/real_009_
python process_raw_images.py data/real/real010.jpg /tmp/output/real_010_
python process_raw_images.py data/real/real011.jpg /tmp/output/real_011_
python process_raw_images.py data/real/real012.jpg /tmp/output/real_012_
python process_raw_images.py data/real/real013.jpg /tmp/output/real_013_
python process_raw_images.py data/real/real014.jpg /tmp/output/real_014_
python process_raw_images.py data/real/real015.jpg /tmp/output/real_015_
python process_raw_images.py data/real/real016.jpg /tmp/output/real_016_
python process_raw_images.py data/real/real017.jpg /tmp/output/real_017_
python process_raw_images.py data/real/real018.jpg /tmp/output/real_018_
python process_raw_images.py data/real/real019.jpg /tmp/output/real_019_
python process_raw_images.py data/real/real020.jpg /tmp/output/real_020_
python process_raw_images.py data/real/real021.jpg /tmp/output/real_021_
python process_raw_images.py data/real/real022.jpg /tmp/output/real_022_
python process_raw_images.py data/real/real023.jpg /tmp/output/real_023_
python process_raw_images.py data/real/real024.jpg /tmp/output/real_024_
python process_raw_images.py data/real/real025.jpg /tmp/output/real_025_
python process_raw_images.py data/real/real026.jpg /tmp/output/real_026_
python process_raw_images.py data/real/real027.jpg /tmp/output/real_027_
python process_raw_images.py data/real/real028.jpg /tmp/output/real_028_
python process_raw_images.py data/real/real029.jpg /tmp/output/real_029_
python process_raw_images.py data/real/real030.jpg /tmp/output/real_030_
python process_raw_images.py data/real/real031.jpg /tmp/output/real_031_
python process_raw_images.py data/real/real032.jpg /tmp/output/real_032_
python process_raw_images.py data/real/real033.jpg /tmp/output/real_033_
